{{ $scheme := "http" }}
{{ if eq (include "nextcloud.certAvailable" .) "true" }}
{{ $scheme = "https" }}
{{ end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-config
data:
  protocol: {{ $scheme }}
